# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b64e6a6c160ab84c7805f6a2522c4c9"
name = "tushar-final-cart"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/app/shop_currenacy_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_cart_transforms,write_discounts,write_products,write_app_proxy"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "/optimaio-cart"
prefix = "apps"
subpath = "optimaio-cart"

